# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4b2c7715e568cee981f7cb163408d08f"
name = "tulipy"
handle = "tulipy"
application_url = "https://roland-element-persistent-hiking.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "tulipy-delivery.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_products"

[auth]
redirect_urls = [
  "https://roland-element-persistent-hiking.trycloudflare.com/auth/callback",
  "https://roland-element-persistent-hiking.trycloudflare.com/auth/shopify/callback",
  "https://roland-element-persistent-hiking.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
